CREATE DATABASE IF NOT EXISTS student_db;
USE student_db;

CREATE TABLE students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    roll_number VARCHAR(15) UNIQUE NOT NULL,
    name VARCHAR(50),
    email VARCHAR(100)
);

INSERT INTO students (roll_number, name, email) VALUES
('M23CSA019', 'PRAVIN', 'M23CSA019@IITJ.AC.IN'),
('M23CSA100', 'RAJU', 'M23CSA100@IITJ.AC.IN'),
('M23CSA101', 'SONU', 'M23CSA101@IITJ.AC.IN');
